version: '2'

services:
  dbt_airflow:
    image: dbt_airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgresqlairflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - '8080:8080' # for airflow web ui
      - '8001:8001' # for dbt docs
    volumes:
      - ./dbt:/my_app/dbt
      - ./extract_load_scripts:/my_app/extract_load_scripts
      - /root/.dbt/:/root/.dbt/
      - ./airflow/dags:/root/airflow/dags
      - ./dbt_airflow_on_startup.sh:/dbt_airflow_on_startup.sh
    command: /bin/bash /dbt_airflow_on_startup.sh
    depends_on:
      - postgres_airflow

  postgres_airflow:
    image: postgres 
    environment:
        - POSTGRES_DB=airflow
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
    hostname: postgresqlairflow
    volumes:
      - ./postgre_data_airflow:/var/lib/postgresql/data:rw

  postgres_metabase:
    image: postgres 
    environment:
        - POSTGRES_DB=metabase
        - POSTGRES_USER=metabase
        - POSTGRES_PASSWORD=metabase
    hostname: postgresqlmetabase
    volumes:
      - ./postgre_data_metabase:/var/lib/postgresql/data:rw
    command: -p 5433

  metabase:
    image: metabase/metabase:latest
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5433
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgresqlmetabase
      - JAVA_TIMEZONE=Europe/Paris
    depends_on:
      - postgres_metabase
    ports:
      - '3000:3000'
    restart: always  